export enum Process {
  SoleToJoint = "soletojoint",
  ChangeOfName = "changeofname",
}

export enum State {
  ApplicationInitialised = "ApplicationInitialised",
  EnterNewName = "EnterNewName",
  NameSubmitted = "NameSubmitted",
  DocumentsRequestedDes = "DocumentsRequestedDes",
  DocumentsRequestedAppointment = "DocumentsRequestedAppointment",
  DocumentsAppointmentRescheduled = "DocumentsAppointmentRescheduled",
  DocumentChecksPassed = "DocumentChecksPassed",
  ApplicationSubmitted = "ApplicationSubmitted",
  TenureInvestigationFailed = "TenureInvestigationFailed",
  TenureInvestigationPassed = "TenureInvestigationPassed",
  TenureInvestigationPassedWithInt = "TenureInvestigationPassedWithInt",
  InterviewScheduled = "InterviewScheduled",
  InterviewRescheduled = "InterviewRescheduled",
  HOApprovalFailed = "HOApprovalFailed",
  HOApprovalPassed = "HOApprovalPassed",
  TenureAppointmentScheduled = "TenureAppointmentScheduled",
  TenureAppointmentRescheduled = "TenureAppointmentRescheduled",
  NameUpdated = "NameUpdated",
  ProcessClosed = "ProcessClosed",
  ProcessCancelled = "ProcessCancelled",
  SelectTenants = "SelectTenants",
  AutomatedChecksFailed = "AutomatedChecksFailed",
  AutomatedChecksPassed = "AutomatedChecksPassed",
  ManualChecksFailed = "ManualChecksFailed",
  ManualChecksPassed = "ManualChecksPassed",
  BreachChecksFailed = "BreachChecksFailed",
  BreachChecksPassed = "BreachChecksPassed",
  TenureUpdated = "TenureUpdated",
  ProcessCompleted = "ProcessCompleted",
}

export enum Status {
  AwaitingTenantsNewName = "Awaiting tenant's new name",
  AwaitingProposedTenantSelection = "Awaiting proposed tenant selection",
  AwaitingFurtherEligibilityChecks = "Awaiting further eligibility checks",
  AwaitingHOEligibilityChecks = "Awaiting Housing Officer eligibility checks",
  RequestSupportingDocuments = "Request supporting documents",
  AwaitingSupportingDocumentsDES = "Awaiting supporting documents through DES",
  AwaitingSupportingDocumentsAppointment = "Awaiting supporting documents appointment",
  SubmitForTI = "Submit for Tenure investigation",
  AwaitingTI = "Awaiting Tenure investigation",
  AwaitingHOReview = "Awaiting Housing Officer review",
  AwaitingTIInterview = "Awaiting Tenure Investigation Interview",
  ScheduleTenancySigningAppointment = "Schedule new tenancy signing appointment",
  AwaitingTenancySigningAppointment = "Awaiting new tenancy signing appointment",
  ProcessCompletedNotify = "Process completed - notify resident",
  ProcessCompleted = "Process completed",
  ProcessClosedNotify = "Process closed - notify resident",
  ProcessClosed = "Process Closed",
  ProcessCancelled = "Process Cancelled",
}

export enum Trigger {
  CancelProcess = "CancelProcess",
  CheckTenancyBreach = "CheckTenancyBreach",
  CheckManualEligibility = "CheckManualEligibility",
  CheckAutomatedEligibility = "CheckAutomatedEligibility",
  CloseProcess = "CloseProcess",
  HOApproval = "HOApproval",
  RequestDocumentsAppointment = "RequestDocumentsAppointment",
  RescheduleDocumentsAppointment = "RescheduleDocumentsAppointment",
  ScheduleInterview = "ScheduleInterview",
  RescheduleInterview = "RescheduleInterview",
  ScheduleTenureAppointment = "ScheduleTenureAppointment",
  RescheduleTenureAppointment = "RescheduleTenureAppointment",
  ReviewDocuments = "ReviewDocuments",
  RequestDocumentsDES = "RequestDocumentsDES",
  RequestDocumentsDes = "RequestDocumentsDes",
  SubmitApplication = "SubmitApplication",
  TenureInvestigation = "TenureInvestigation",
  UpdateName = "UpdateName",
  UpdateTenure = "UpdateTenure",
  EnterNewName = "EnterNewName",
  CompleteProcess = "CompleteProcess",
}
